version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php-clean
    image: viniciusac/php
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks:
      - app-php-clean

  nginx:
    image: nginx:latest
    container_name: app-nginx-clean
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php-clean
    
networks:
  app-php-clean:
    driver: bridge